[package]
name = "fhedb-core"
version = "0.1.0"
edition = "2024"

[dependencies]
fhedb-types = { path = "../fhedb-types" }
bson = { version = "3.0.0", features = ["serde"] }
uuid = "1.18.1"
chrono = "0.4.42"

[dev-dependencies]
tempfile = "3.22.0"
